### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: 523 undefined

### ISSUE THREAD

**Issue by AlfaJackal** [iDerp/Pi-Hole-for-LaMetric#14]
Newly got this error. Any ideas how to fix that?
```
pi@Eggman:~/Pi-Hole-for-LaMetric $ node index.js 
Starting Pi-Hole for LaMetric v2.0.3-Beta...
⠋ Testing Pi-Hole Connection @ 10.0.0.13...Debug Mode Enabled
✔ Pi-Hole Connection @ 10.0.0.13 Successful!
✔ Pi-Hole Auth Valid!
✔ Connected to "Rayman" @ 10.20.0.22 running OS v2.0.24 & Pi-Hole Status v5! (XXX)
ℹ Up to date.
⠸ Sending update for "Rayman" @ 10.20.0.22 to the server...(node:3678) UnhandledPromiseRejectionWarning: Error: 523 undefined
    at /home/pi/Pi-Hole-for-LaMetric/node_modules/snekfetch/src/index.js:193:21
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:3678) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3678) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate th⠏ Sending update for "Rayman" @ 10.20.0.22 to the server
```

**Comment by AlfaJackal** [comment]
Didn’t do anything and it works again. Could you please tell us why this occurres so often?!

**Comment by iDerp** [comment]
This was most likely a server issue back then, hopefully you haven't gotten it often at all since

**Comment by AlfaJackal** [comment]
Hi @iDerp, 

I am having this issue again. Is there anything wrong with the server?

Best,
AlfaJackal

**Comment by iDerp** [comment]
Hi, yes the server was down. Everything should be all set now, might take up to 24 hours though for the Lametric to notice its back online. Just make sure you update the app on Lametric if it doesn't automatically.

**Comment by AlfaJackal** [comment]
Thank you!

Any chances for self-hosting this one?

**Comment by AlfaJackal** [comment]
> Hi, yes the server was down. Everything should be all set now, might take up to 24 hours though for the Lametric to notice its back online. Just make sure you update the app on Lametric if it doesn't automatically.

Back home now and tried it again: Doesn't work, unfortunately. ![image](https://user-images.githubusercontent.com/17096950/129751262-fd42a380-1524-4c1b-8ea6-36a5a23fbc5c.jpeg)

App is up to date, also LaMetric firmware.

**Comment by iDerp** [comment]
I'll have to take a look into whats going on. It should be set, but knowing me I might've skipped a simple step

**Comment by iDerp** [comment]
I did skip a step, I just updated the client program (this repo) so once you pull that it should work.

**Comment by AlfaJackal** [comment]
> I did skip a step, I just updated the client program (this repo) so once you pull that it should work.

Yeah, saw your edit and pulled it. Works:
![image](https://user-images.githubusercontent.com/17096950/129863285-bd555b12-ec4b-4930-a5d7-e70905be25a1.jpeg)

Thank you very much!

One last question: Have you already thought about a self-hosting solution?

**Comment by AlfaJackal** [comment]
OK, something is still fishy here: Connection, as you can see above, has been made but LaMetric still shows no data - only this screen:
![image](https://user-images.githubusercontent.com/17096950/129892422-c3d986be-7260-422f-acde-cf5d592e3b29.jpeg)

LaMetric App (Version 5) has been reinstalled, restarted LaMetric, restarted script - no data on my LaMetric.

**Comment by AlfaJackal** [comment]
Any update on that issue?

**Comment by iDerp** [comment]
Interesting, I haven’t touched it in a while, so I’ll have to check what’s going on. I should have an answer by some time tonight.

**Comment by iDerp** [comment]
> 
> 
> Any update on that issue?

On my end, I didn't notice anything different. The server is still receiving requests. Are you still having this issue?

**Comment by AlfaJackal** [comment]
> 
> 
> > Any update on that issue?
> 
> On my end, I didn't notice anything different. The server is still receiving requests. Are you still having this issue?

Thanks for looking into it! Yes, unchanged and not working. I just deleted the app on LaMetric and wanted to reinstall it, but it is not in the LaMetric Store anymore: https://apps.lametric.com/apps/pi-hole_status/6943 

Also searching for "Pi-Hole", "pihole", "Pi Hole", etc. does not find your app.

**Comment by iDerp** [comment]
Strange. I did receive an email from LaMetric (automated) recently about it not working, so maybe they changed something in their API or something like that, which wouldn't surprise me considering how long this app has been around. I'll have to take a look at it tomorrow and I'll update you then.
________________________________

**Comment by AlfaJackal** [comment]
It is. 

Thanks for looking in it. There is no hurry - would be glad if you'll manage to fix it. Love your app! 🤩

**Comment by iDerp** [comment]
*Should* be all set now. Seems like I forgot to change the URL when I moved the server.

**Comment by AlfaJackal** [comment]
> *Should* be all set now. Seems like I forgot to change the URL when I moved the server.

Installed the app again, fired up the script ... works like a charm now! That was it! :) Thank you again! 🤘
