### ISSUE TITLE
Stuck on "Sending update to server"

### ISSUE THREAD

**Issue by ipr0ute** [iDerp/Pi-Hole-for-LaMetric#16]

**Comment by ipr0ute** [comment]
I'm stuck on "Sending update to the server..." I'm not sure what to do next.

d:\Pi-Hole-for-LaMetric-stable>node index.js
Starting Pi-Hole for LaMetric v2.0.3-Beta...
√ Pi-Hole Connection @ 192.168.1.101 Successful!
√ Pi-Hole Auth Valid!
√ Connected to "My LaMetric" @ 192.168.1.88 running OS v2.1.1 & Pi-Hole Status v5! (#####################)
i Up to date.
- Sending update for "My LaMetric" @ 192.168.1.88 to the server...

**Comment by iDerp** [comment]
Do you still have this issue?
