### ISSUE TITLE
Unhandled promise rejection error

### ISSUE THREAD

**Issue by HariComputes** [iDerp/Pi-Hole-for-LaMetric#17]
Hi,

Here is the console output:
`
Starting Pi-Hole for LaMetric v2.0.3-Beta...
✔ Pi-Hole Connection @ 192.168.0.61 Successful!
✔ Pi-Hole Auth Valid!
✔ Connected to "My LaMetric" @ 192.168.0.53 running OS v2.1.2 & Pi-Hole Status v5! (####################)
ℹ Up to date.
⠙ Connecting to LaMetric @ 192.168.0.53...(node:204687) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at snek.get.set.then.LaMetricDeviceInfo2 (/root/Pi-Hole-for-LaMetric/index.js:74:109)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:204687) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:204687) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Node version is v10.21.0

System details:
`
    Icon name: computer-vm
    Chassis: vm
    Virtualization: microsoft
    Operating System: CentOS Linux 8 (Core)
    CPE OS Name: cpe:/o:centos:centos:8
    Kernel: Linux 4.18.0-193.19.1.el8_2.x86_64
    Architecture: x86-64
`

This doesn't seem to be sending the data over to the LaMetric, and loops the sending with no successful "sent" output on the console.

Is there any ports that require to be opened?

I have removed/censored any details i'm unwilling to share.
Let me know if you need any more details. Unluckily i'm not proficient in node js code.

I look forward to your response.
Thanks

Edit: I've tested Node versions 6.13.0; 8.9.0; 9.4.0 and 10.21.0. The software wouldn't run on 6.13.0. All other version produce similar to same outcomes.

Edit2: I've tested previous versions of this program. (2.0.2 and 2.0.1) with same issue/outcomes.

**Comment by iDerp** [comment]
Sorry for the extremely late response. Are you still having issues with it? It hasn't been updated for some time and sometimes that causes issues.

**Comment by HariComputes** [comment]
Hi,

I didn't bother any further with this.

I've created a new PiHole Server and i decided to re-test this by doing the install for this by scratch and it still doesn't seem to work.

I'll close the issue as i'm no longer looking to add this functionality.

Thanks anyway

**Comment by iDerp** [comment]
No worries, if you ever decide to try and set this up again and are having issues, feel free to reach out. Or if you want to make your own of some sort, I can also help give tips if needed. 

FYI the server for this is actually currently down as of a few days ago while I’m moving it. 

Thanks again for your interest in this
