### ISSUE TITLE
Bad gateway?

### ISSUE THREAD

**Issue by malmentm** [iDerp/Pi-Hole-for-LaMetric#4]
Trying to run this on my pihole and get the folowwing error.. any ideas?

 Sending update for "LaMetric" @ 192.168.1.64 to the server...(node:11932) ExperimentalWarning: The http2                                                                            module is an experimental API.
⠦ Sending update for "LaMetric" @ 192.168.1.64 to the server...(node:11932) UnhandledPromiseRejectionWarnin                                                                           g: Error: 502 Bad Gateway
    at _response.transport.request.then (/home/pi/Pi-Hole-for-LaMetric/node_modules/snekfetch/src/index.js:                                                                           193:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:11932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by                                                                            throwing inside of an async function without a catch block, or by rejecting a promise which was not handle                                                                           d with .catch(). (rejection id: 2)
(node:11932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, prom                                                                           ise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by malmentm** [comment]
Great thanks. You don't happen to know how to make this index.js autorun when raspberry pi starts?

**Comment by iDerp** [comment]
You're welcome, and no I don't know off hand
