### ISSUE TITLE
Lametric queries lametric.b1nzy.xyz every 5 seconds with plugin installed.

### ISSUE THREAD

**Issue by malmentm** [iDerp/Pi-Hole-for-LaMetric#6]
Lametric queries lametric.b1nzy.xyz every 5 seconds with plugin installed. Is it necessary?

**Comment by iDerp** [comment]
I will fix this to pull every minute instead of every 5 seconds.

On Nov 5, 2018, at 13:54, malmentm <notifications@github.com<mailto:notifications@github.com>> wrote:


Lametric queries lametric.b1nzy.xyz<http://lametric.b1nzy.xyz> every 5 seconds with plugin installed.

**Comment by malmentm** [comment]
Whats is it pulling every 5 sec?

**Comment by iDerp** [comment]
It's currently pulling new data every 5 seconds, which is a bit overkill

On Nov 5, 2018, at 13:57, malmentm <notifications@github.com<mailto:notifications@github.com>> wrote:


Whats is it pulling every 5 sec?

**Comment by malmentm** [comment]
Can you make it an option so we can Control how often it will pull new data?

**Comment by iDerp** [comment]
That is set on the app side, it can't be changed by the user

On Nov 5, 2018, at 13:59, malmentm <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you make it an option so we can Control how often it will pull new data?

**Comment by malmentm** [comment]
I noticed also that Latest blocket Query also shows [OBJECT OBJECT]

**Comment by iDerp** [comment]
I'll be sure to fix that for the update also

**Comment by malmentm** [comment]
Will you also change "Today" to "Last 24hrs" ?

**Comment by iDerp** [comment]
Sure!

**Comment by malmentm** [comment]
Can you also change the text displayed on the lametric to "Past 24 Hours" for DNS Queries, ADs Blocked and Total Client Seen? PiHole now reports stats in the form of last 24 hours and does not reset every midnight :)

"XXXX ADS BLOCKED IN THE PAS 24 HOURS"
"XXXX DNS QUERIES IN THE PAST 24 HOURS"
"XXXX CLIENT SEEN IN THE PAST 24 HOURS"

**Comment by iDerp** [comment]
Sure, I can do that from the server side so no update will be needed for that

**Comment by malmentm** [comment]
Ok, well I don't really know what looks best I might look better with just
"XXXX ADS BLOCKED"
"XXXX DNS QUERIES"
"XXXX CLIENTS SEEN"
As this is what the PiHole GUI shows. Or what do you think? We already knows this is for the past 24 hours as this is how PiHole works. (Past 24h) is ju redundant information :)

**Comment by malmentm** [comment]
Could you change to ..

"XXXX ADS BLOCKED"
"XXXX DNS QUERIES"
"XXXX CLIENTS SEEN"

I think less text is important on the lametric. Short and effective :) And it matched how the PiHole WebGUI displays the data
