### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: 522 undefined

### ISSUE THREAD

**Issue by malmentm** [iDerp/Pi-Hole-for-LaMetric#8]
Got this now :=)

Nov 06 21:09:11 raspberrypi pilametric[2171]: (node:2171) UnhandledPromiseRejectionWarning: Error: 522 undefined
Nov 06 21:09:11 raspberrypi pilametric[2171]:     at _response.transport.request.then (/home/pi/Pi-Hole-for-LaMetric/node_modules/snekfetch/src/index.js:193:21)
Nov 06 21:09:11 raspberrypi pilametric[2171]:     at <anonymous>
Nov 06 21:09:11 raspberrypi pilametric[2171]:     at process._tickCallback (internal/process/next_tick.js:182:7)
Nov 06 21:09:11 raspberrypi pilametric[2171]: (node:2171) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch
Nov 06 21:09:11 raspberrypi pilametric[2171]: (node:2171) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Jonovich** [comment]
Likewise :(

**Comment by rainmanjam** [comment]
same

**Comment by jolu1705** [comment]
Same here
