### ISSUE TITLE
Connected to PiHole and Lametric but still no data shown on Lametric screen

### ISSUE THREAD

**Issue by zerocrashhh** [iDerp/Pi-Hole-for-LaMetric#9]
PiHole installed on Ubuntu 18.04 VM

:~/Pi-Hole-for-LaMetric$ node index.js
Starting Pi-Hole for LaMetric v2.0.1...
✔ Pi-Hole Connection @ 192.168.88.250 Successful!
✔ Pi-Hole Auth Valid!
✔ Connected to "My LaMetric" @ 192.168.88.54 running OS v2.0.17 & Pi-Hole Status                                                         v4! (SAXX04XXXXXXXXXXXX9)
✖ Connection to LaMetric @ 0.0.0.0 Failed. LaMetric does not seem to linked to t                                                        his IP.
ℹ Up to date.
⠙ Connecting to LaMetric @ 192.168.88.54...(node:1577) UnhandledPromiseRejection                                                        Warning: TypeError: Cannot read property 'toString' of undefined
    at snek.get.set.then.LaMetricDeviceInfo2 (/home/milan1201/Pi-Hole-for-LaMetr                                                        ic/index.js:71:112)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:1577) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This                                                         error originated either by throwing inside of an async function without a catch                                                         block, or by rejecting a promise which was not handled with .catch(). (rejection                                                         id: 1)
(node:1577) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre                                                        cated. In the future, promise rejections that are not handled will terminate the                                                         Node.js process with a non-zero exit code.
⠼ Sending update for "My LaMetric" @ 192.168.88.54 to the server...⠋ Connecting                                                         ⠙ Connecting to LaMetric @ 192.168.88.54...(node:1577) UnhandledPromiseRejection                                                        Warning: TypeError: Cannot read property 'toString' of undefined
    at snek.get.set.then.LaMetricDeviceInfo2 (/home/milan1201/Pi-Hole-for-LaMetr                                                        ic/index.js:71:112)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:1577) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This                                                         error originated either by throwing inside of an async function without a catch                                                         block, or by rejecting a promise which was not handled with .catch(). (rejection                                                         id: 2)

> 

VM, PiHole and Lametric all running latest versions.

**Comment by iDerp** [comment]
The server for the app had been down but I had some time and put it back up on the new server. The program should be running fine now. I did have to update the domain so the client app and the lametric app need to be updated on the client end. If you have any more issues, please let me know.

**Comment by zerocrashhh** [comment]
Hi, thanks for such a quick reply.
I deleted the Lametric Pi Hole Status app and installed it again, and on the VM removed the folder cloned it again from github, set the config.json file again, run npm i and node index.js again.

Unfortunately getting the same error:

mil@piholetvs471:~/Pi-Hole-for-LaMetric$ node index.js
Starting Pi-Hole for LaMetric v2.0.2...
✔ Pi-Hole Connection @ 192.168.88.250 Successful!
✔ Pi-Hole Auth Valid!
✔ Connected to "My LaMetric" @ 192.168.88.54 running OS v2.0.17 & Pi-Hole Status v5! (SA1704XXXXXXXXX)
✖ Connection to LaMetric @ 0.0.0.0 Failed. LaMetric does not seem to linked to this IP.
ℹ Up to date.
⠙ Connecting to LaMetric @ 192.168.88.54...(node:20404) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at snek.get.set.then.LaMetricDeviceInfo2 (/home/milan1201/Pi-Hole-for-LaMetric/index.js:75:112)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:20404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20404) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Let me know what you want me to do to test and make it work.

**Comment by iDerp** [comment]
Right after line 67, add this line on a new line
```
console.log(PiHoleTopItemsData.body)
```
Then let me know the output

**Comment by malmentm** [comment]
Will there be a server free version?

**Comment by iDerp** [comment]
Eventually yes, the current issue you have seems to be LaMetric related though.

**Comment by zerocrashhh** [comment]
Still no go, will try again in a few days/weeks if it is Lametric related.

Cheers

1201@piholetvs471:~/Pi-Hole-for-LaMetric$ node index.js
Starting Pi-Hole for LaMetric v2.0.2...
✔ Pi-Hole Connection @ 192.168.88.250 Successful!
✔ Pi-Hole Auth Valid!
✔ Connected to "My LaMetric" @ 192.168.88.54 running OS v2.0.17 & Pi-Hole Status v5! (SA170XXXXXXXXXX)
✖ Connection to LaMetric @ 0.0.0.0 Failed. LaMetric does not seem to linked to this IP.
ℹ Up to date.
⠙ Connecting to LaMetric @ 192.168.88.54...{ top_queries:
   { 'speedtest.sbb.rs': 5504,
     'speedtest.beotel.net': 4254,
     'speedtest.telenor.rs': 1932,
     'speedtest.mts.rs': 1154,
     'www.speedtest.net': 768,
     'speedtest.vektor.net': 642,
     'speedtest.vipmobile.rs': 254,
     '1.0.0.1.in-addr.arpa': 26,
     '1.1.1.1.in-addr.arpa': 26,
     'api.snapcraft.io': 16 },
  top_ads: [] }
(node:6553) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at snek.get.set.then.LaMetricDeviceInfo2 (/home/milan1201/Pi-Hole-for-LaMetric/index.js:76:112)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:6553) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6553) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠧ Sending update for "My LaMetric" @ 192.168.88.54 to the server...^C

**Comment by iDerp** [comment]
Sorry, I meant PiHole related. It seems that there may have been a change to PiHole since I made this. This should be a simple fix for now. What I will do is temporarily remove the Last Blocked Query value until I can mess around with PiHole myself. Until I can, I pushed out a new client update that should fix it. No need to do an update for the app on the LaMetric for this one.
